### PR TITLE
Product get and set tests

### LINKED ISSUE #4: User should be able to add a product for a customer
**Given** a customer has been made active in the program
**When** the user selects the option to add a product
**Then** the user should be prompted to enter in all appropriate information for a product
**And** when complete, the product should be added for the active customer

### PR DESCRIPTION
**Pull request by madelineepower**
## Changes proposed in this pull request: 
- Create product test creates a product, creates a row in the database, then check the id of the product that was added
- Get product test retrieves a product id
- Add product type

## How to test: 
- REQUIRED: An active customer
-SEED THE DATABASE: delete your db file and dotnet run to initialize the database

## NEXT STEPS FOLLOWING REGROUP
- write test for Product Model and Product Type Model

@EnRonSwanson/

### CODE REVIEW

**Comment by arock83** [comment]
👍 can't test, dependent on other code but it looks good

**Comment by hannahhall** [comment]
Don't forget to write a test for the Product model. Here's an example of a test for a model: https://github.com/teamBangazon/BangazonCLI/blob/master/Bangazon.Tests/Bangazon_CustomerShould.cs

**Comment by mitchellblom** [comment]
👍 merging this code base to have the same master before the weekend. No conflicts, and a couple dependencies to match up with Ryan's tests.

**Comment by therealrmac** [comment]
👍

**Pull request merged**
