### PR TITLE
added model file for orderProduct table

### PR DESCRIPTION
**Pull request by arock83**
## Fixes 
# Adds the OrderProduct Model

## Changes proposed in this pull request: 
- creates a OrderProduct.cs file in the model folder

## How to test: 
- No Testing available yet, just verify that all fields are correct

@EnRonSwanson/

### CODE REVIEW

**Comment by mitchellblom** [comment]
looks good. will need this later.

**Comment by mitchellblom** [comment]
@therealrmac needs to close this one. i closed it by mistake.

**Comment by therealrmac** [comment]
Does it need a constructor to go along with it? Or because its a join table it doesn't need it?

**Comment by arock83** [comment]
Doesn't need a constructer atm.  will add later, as the methods and tests are fleshed out

**Comment by madelineepower** [comment]
👍

**Pull request merged**
